source cfssl/cfssl-installer.sh
cd kubectl
source kubectl-installer.sh
cd ..
cd certs
source generate.sh
cd ..
cd etcd
source etcd-installer.sh
cd ..
source generate-cluster-components-configs.sh
source bootstrap-kubernetes-controller.sh